// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using AzureBooks.Models;
using Newtonsoft.Json.Linq;

namespace AzureBooks.Models
{
    public static partial class BookCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Book> DeserializeJson(JToken inputObject)
        {
            IList<Book> deserializedObject = new List<Book>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Book book = new Book();
                book.DeserializeJson(iListValue);
                deserializedObject.Add(book);
            }
            return deserializedObject;
        }
    }
}
